### ISSUE TITLE
Ensure tree traversal operations (e.g. Node::getDescendantNodesAndTokens) are passing by reference

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/tolerant-php-parser#23]
Otherwise we end up unnecessarily doubling peak memory while iterating through nodes/tokens.

**Comment by nikic** [comment]
Which part would be by reference here?

As a performance tip, code like https://github.com/Microsoft/tolerant-php-parser/blob/2e0edb3bdec64425406ec79b9ff3088e96afac85/src/Node.php#L100 can be written as

```
yield from $child->getDescendantNodesAndTokens($shouldDescendIntoChildrenFn);
```

(The keys will be different, but I assume this doesn't matter?)

The advantage is that when using `yield from` PHP is able to directly resume the innermost generator, while a manual `foreach` + `yield` requires going through all generators in the chain.

**Comment by mousetraps** [comment]
One repro is that if you add the following to `validation/ParserPerformance.php` (right after the `SplFixedArray::fromArray` line), you'll see that the peak memory usage is twice that of just holding all the ASTs in memory.

```
foreach ($asts as $ast) {
    foreach ($ast->getDescendantNodesAndTokens() as $node) {
        $a = $node;
    }
}
```

I attempted a fix I thought would work (https://github.com/mousetraps/tolerant-php-parser/commit/4f13aed32ae35b4db0cb00627bc60295aa9266e4), but it doesn't seem to have helped.

Re: "yield from" + keys - how exactly do the keys differ in the end? In the particular example you pointed to, I would expect it to work fine (we only care about whether it's the first Node, because if so, we'll strip away trivia). Ultimately, I think the primary thing we want to guarantee is that the Nodes are traversed in a logical order, and the keys could be whatever they want.

**Comment by nikic** [comment]
Ah, I see the problem now: `getChildNodesAndToken()` is iterating over `get_object_vars($this)`, which will force the creation of a properties hashtable on the object, effectively doubling memory usage (tbh, I'm surprised it only doubles memory usage). Doing a direct `foreach ($this as $val)` won't solve this either, as it essentially does the same thing internally.

Ideally this is something we can resolve in PHP, by allowing the iteration of objects with only declared properties without reconstructing the properties HT. You probably still need some workaround for this in the meantime... In php-parser I have a `getSubNodeNames()` method on each node, which gives me the keys to iterate over. This is partly motivated by wanting to avoid reconstruction of the properties HT. To avoid manually specifying this, what you could do is to use reflection to programmatically collect all declared properties, and then cache this result. Admittedly this is rather ugly, but I can't think of an easier way right now.

As to `yield from`: The difference in the keys is that `yield from` retains the original keys, while the current code reindexes everything. Because `yield from` retains keys, you will end up keys occurring multiple times. As such, checking for a `0` key will no longer work. Instead would have to use a flag to check for the first value or something. From a quick test using `yield from` is worthwhile though, it drops execution time for your snippet from 3.2s to 2s for me.

**Comment by mousetraps** [comment]
@nikic - nice find! And agreed that it makes sense to use `yield from` where we can - and if there is a case where the indices *really* matter, then this is something we can expose as a flag in the API.

**Comment by mousetraps** [comment]
Also, it's ugly, but good enough for now, and we can plan to ditch the reflection as soon as the API is a little more stable.
