### ISSUE TITLE
What about PSR-1, PSR-2 and PSR-12 codestyle?

### ISSUE THREAD

**Issue by SerafimArts** [Microsoft/tolerant-php-parser#46]
Do you plan to format your code to a single php global recommendations? 

If not, why not?

**Comment by mousetraps** [comment]
Hey @SerafimArts! We'll probably to standardize on [PSR-12](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md), with a couple explicit exceptions (the biggest one being that opening braces should be on the same line everywhere both because it increases consistency within the codebase, and because it helps to keep the code "tighter" which I find is especially helpful for this project in particular.)

**Comment by SerafimArts** [comment]
> with a couple explicit exceptions

Once the new standard from Microsoft... Сan once you begin to follow all recommendations? :D

**Comment by SerafimArts** [comment]
@nikic It would be interesting nevertheless interesting to hear your opinion why you pooschraesh violation of generally accepted norms

**Comment by mousetraps** [comment]
@SerafimArts It's a curly brace, not PSR-Microsoft-Update-2-Professional-Edition. Can we please keep these conversations constructive and refrain from blowing things out of proportion? Thanks :heart:

**Comment by nikic** [comment]
@SerafimArts Because I don't think it's a big deal to deviate from a coding standard on specific points, and I can certainly empathize with the [reasons outlined elsewhere](https://github.com/Microsoft/tolerant-php-parser/issues/50#issuecomment-275257758). A coding standard is a means to an end, not an end in itself. Furthermore, I consider your comment, at least in its in initial form, to be in poor taste.
