### ISSUE TITLE
Parser Class Refactoring

### ISSUE THREAD

**Issue by decanus** [Microsoft/tolerant-php-parser#50]
Parser class could potentially be split up to make the code more legible.

**Comment by mousetraps** [comment]
Hey @decanus! I *totally* get where you're coming from - a 3K line file should certainly make one go "huh?", but I don't think we're going to split it up into multiple classes or files any time soon. Having worked on the project for a few months (and also having read through both the TypeScript and Roslyn source code), I've found having the parser logic contained within a single file to be much easier to both read and work with because it really helps with code navigation.

Additionally, it depends on what specifically what refactorings you were thinking, but in addition to readability, there are also some performance considerations to keep in mind - e.g. we might decide to sacrifice some readability in order to reduce the number of function calls. 

That said, I'm open to hearing about other ways you think readability could be improved - e.g. change the ordering/structure of the code, add some more comments, improved method/property-naming, or interfaces between the lexer/parser (which we'll definitely need to do when we get to incremental parsing), etc. 

Closing this issue because it feels like the general topic of refactoring might be a little too "broad", but very much open to any other suggestions you might have to increase readability, either in the form of an issue or PR :smiley:.

**Comment by decanus** [comment]
I feel like a lot of optimisations could be done to try and clean up the code. There seems to be a lot of functions that are excessively long. Sticking to a code style could also help, some of the current code looks like it didn't conform to any style.

**Comment by mousetraps** [comment]
Agreed, definitely needs some cleanup - ultimately it was a balance between ironing out all the loose ends and releasing earlier so we get it in the hands of awesome people like you :wink:. re: code style - see #46 for thoughts. The biggest things I'm attached to are single file lexer/parser and open-braces on same line. For most everything else, going with standard PHP best practices seems appropriate.

**Comment by decanus** [comment]
@mousetraps Sounds good, in that case I'll open some refactoring PR's

**Comment by mousetraps** [comment]
@decanus not sure I understand - could you give an example?

**Comment by mousetraps** [comment]
Oh, I get it now - you mean you feel
```php
function a () : int
{
}
```
is more readable than 
```
function a () : int {

}
```

**Comment by decanus** [comment]
Yeah exactly

**Comment by mousetraps** [comment]
Ultimately it comes down to:
* I *really* dislike the inconsistency in braces on same line vs. not same line within the same file (e.g. ifs vs. functions).
* as mentioned in #46, keeping the code tighter helps a lot with readability/scannability, especially in the case of this project, because you can see more on a single screen
* re: return type declarations - I actually prefer the second version, perhaps partly because I'm used to TypeScript

**Comment by mattacosta** [comment]
> Having worked on the project for a few months (and also having read through both the TypeScript and Roslyn source code), I've found having the parser logic contained within a single file to be much easier to both read and work with because it really helps with code navigation.

Well at least there's 1 other person out there that knows the pain of trying to read Lexer.cs/Lexer_StringLiteral.cs, and LanguageParser.cs/LanguageParser_InterpolatedString.cs. 

After going through scanner.ts, anything reasonable to keep the line count down gets a +1 from me.
